### ISSUE TITLE
Docker container crashes

### ISSUE THREAD

**Issue by Green-Kite** [leafac/kill-the-newsletter#103]
First of all @leafac thank you for this great piece of work!

I've been using the hosted service for a few weeks but since I'm selfhosting most services I tried to deploy the docker container as well. I can reach the frontend and creating and subscribing to new feeds works well.

But I can't get the Mailserver part working. Every time I'm sending a mail to KtN the docker container crashes and restarts.
This is the log:

```
2024/05/26 17:35:14	(Use `node --trace-deprecation ...` to show where the warning was created)
2024/05/26 17:35:14	(node:19) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
2024/05/26 17:35:04	    at processImmediate (node:internal/timers:478:21)
2024/05/26 17:35:04	    at Immediate.<anonymous> (/kill-the-newsletter/node_modules/smtp-server/lib/smtp-server.js:364:39)
2024/05/26 17:35:04	    at /kill-the-newsletter/node_modules/smtp-server/lib/smtp-server.js:100:26
2024/05/26 17:35:04	    at SMTPServer.connect (/kill-the-newsletter/node_modules/smtp-server/lib/smtp-server.js:112:26)
2024/05/26 17:35:04	    at new SMTPConnection (/kill-the-newsletter/node_modules/smtp-server/lib/smtp-connection.js:55:24)
2024/05/26 17:35:04	    at new SMTPStream (/kill-the-newsletter/node_modules/smtp-server/lib/smtp-stream.js:34:21)
2024/05/26 17:35:04	TypeError: Cannot set property closed of #<Writable> which has only a getter
2024/05/26 17:35:04	                    ^
2024/05/26 17:35:04	        this.closed = false;
2024/05/26 17:35:04	/kill-the-newsletter/node_modules/smtp-server/lib/smtp-stream.js:34
```

**Comment by jtagcat** [comment]
While I wish there was, there is no support for Docker. You are opening an issue in the wrong place. Find the third party providing your  deployment components.

**Comment by leafac** [comment]
I suppose this isn’t relevant anymore. I’ll close it for now, but please feel free to follow up if you wish.
