### ISSUE TITLE
Error: /lib64/libm.so.6: version `GLIBC_2.29' not found

### ISSUE THREAD

**Issue by InsaneSplash** [leafac/kill-the-newsletter#61]
Hello,

I am unable to run KTN on RHEL (Oracle Linux) v8

```
/tmp/caxa/kill-the-newsletter--migration/lhofwjpkx7/node_modules/bindings/bindings.js:121
        throw e;
        ^

Error: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/caxa/kill-the-newsletter--migration/lhofwjpkx7/node_modules/better-sqlite3/build/Release/better_sqlite3.node)
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1151:18)
    at Module.load (node:internal/modules/cjs/loader:972:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:996:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at bindings (/tmp/caxa/kill-the-newsletter--migration/lhofwjpkx7/node_modules/bindings/bindings.js:112:48)
    at Object.<anonymous> (/tmp/caxa/kill-the-newsletter--migration/lhofwjpkx7/node_modules/better-sqlite3/lib/database.js:9:24)
    at Module._compile (node:internal/modules/cjs/loader:1092:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
    at Module.load (node:internal/modules/cjs/loader:972:32) {
  code: 'ERR_DLOPEN_FAILED'
}
```

**Comment by leafac** [comment]
Hi @InsaneSplash,

Thanks for reaching out.

I’m afraid you won’t be able to use the binary we distribute for Kill the Newsletter! because your operating system doesn’t include the necessary dependencies (specifically a compatible version of glibc).

I think you have one of two options:

1. Use a different operating system. Perhaps using a virtual machine or a container.
2. Install & build Kill the Newsletter! from source. It isn’t terribly difficult to do: install the latest version of Node.js (I recommend [`nvm`](https://github.com/nvm-sh/nvm) for that; clone the repository; and `npm ci` to install dependencies & build. From there you should be able to start the server by running `node ./distribution/index.js`.

Good luck. Let me know how it goes.
